config/routes.rb
HOOK::Application.routes.draw do
  
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :carts
  
  root to: "static#index"

  resources :line_items

  
  resources :products, only: [:show] do
    resources :line_items, only: [:create]
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy

  def add_product(product_id)
    line_items.find_or_initialize_by(product_id: product_id).increment(:quantity)
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end


end

app/models/color.rb
class Color < ActiveRecord::Base
    belongs_to :product, foreign_key: 'product_id'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
  belongs_to :cart

  def total_price
    product.price * quantity
  end

  def copy_product_attributes(product)
    self.name = product.name
    self.price = product.price
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
    has_many :line_items
    has_many :products, :through => :line_items
  def total
    self.line_items.inject(0) { |sum, item| sum += (item.price * item.quantity) }
  end

  def empty?
    self.line_items.empty?
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  has_many :colors, foreign_key: 'product_id'
  has_many :line_items
  has_many :orders, :through => :line_items

 
  validates :name, :price, :description, :image_url, :presence => true
  before_destroy :ensure_not_referenced_by_any_line_item
 
  #...
 
 
  private
 
    # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_cart
   private
  
     def current_cart 
       Cart.find(session[:cart_id])
     rescue ActiveRecord::RecordNotFound
       cart = Cart.create
       session[:cart_id] = cart.id
       cart
     end

     def set_cart 
      @cart = current_cart 
     end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
# GET /carts/1
# GET /carts/1.xml 
  def show
    begin
      @cart = Cart.find(params[:id]) 
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to "/", :notice => 'Invalid cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @cart }
      end 
    end
  end

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to "/", notice: 'invalid_cart'
  end

  def destroy 
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to "/",
        notice: "Your cart is now empty" }
        format.json { head :no_content }
      end
    end

end

app/controllers/concerns/current_cart.rb
module CurrentCart
  extend ActiveSupport::Concern

  private

    def set_cart
      @cart = Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only:[:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

def line_item_params
  params.require(:line_item).permit(:product_id, :quantity)
end  

def create
  product = Product.find(params[:product_id])
  @line_item = @cart.add_product(product.id)
  @line_item.quantity = params[:line_item][:quantity] || 1


  respond_to do |format| 
    if @line_item.save
      format.html { redirect_to "/#products", notice: "Product added to cart!!" }
      format.xml  { render :xml => @line_item,
        :status => :created, :location => @line_item }
    else
      format.html { render :action => "new" } 
      format.xml { render :xml => @line_item.errors,
        :status => :unprocessable_entity }
      end
    end
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
    @product = Product.find(params[:id])
    @line_item = LineItem.new
  end

  def new
  end

  def edit
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    layout false
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def index
    @products = Product.all
  end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<div id= "cart" name="cart">
<h1>Edit Cart</h1>

<%= render 'form' %>

<%#= link_to 'Show', @cart %> 
</div>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<div id= "cart" name="cart">
<body>

<h2> Your Cart </h2>
<table>
  <% @cart.line_items.each do |item| %>
  <tr>
    <td id="qty"><%= item.quantity %> &times;</td>
    <td><%= item.product.name %> <%= item.product.color %></td>
    <td class="item_price"><%= number_to_currency(item.total_price) %></td> 
    </tr>
  <% end %>

  <tr class="total_line">
    <td colspan="2"> Total </td>
    <td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
  </tr>
</table>
  <%= button_to "Edit Cart", edit_cart_path(@cart), method: :get%>
  <%= button_to "Empty Cart", @cart, method: :delete,
      data: {confirm: "You're Sure Dude..."} %>
</div>
</body>

app/views/line_items/create.html.erb
<h1>LineItems#create</h1>
<p>Find me in app/views/line_items/create.html.erb</p>

app/views/line_items/destroy.html.erb
<h1>LineItems#destroy</h1>
<p>Find me in app/views/line_items/destroy.html.erb</p>

app/views/products/show.html.erb
<!-- <h1><%=@product.name%></h1>
<%= form_for([@product, @line_item]) do |f|%>
<%= f.text_field :quantity %>

<%= f.submit('Add to cart') %>
<% end %> -->